license="MIT"
issueTrackerURL="https://github.com/Elpu7/easy-freecam/issues"

[[mixins]]
config="easy-freecam.mixins.json"

[[mixins]]
config="easy-freecam.client.mixins.json"

[[mods]]
modId="easy_freecam"
namespace="easy-freecam"
version="${mod_version}"
displayName="Easy-freecam"
displayURL="https://modrinth.com/project/easy-freecam"
iconFile="assets/easy-freecam/icon.png"
authors="Elpu7"
description='''A simple, easy-to-use Freecam mod.'''

[[dependencies.easy_freecam]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.easy_freecam]]
modId="elib"
type="required"
versionRange="[${elib_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.easy_freecam]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[features.easy_freecam]
javaVersion="[25,)"
